package com.issueflow.entity;

public enum HistoryEventType {
    ISSUE_CREATED,
    STATUS_CHANGED,
    PRIORITY_CHANGED,
    ASSIGNEE_CHANGED,
    TRIAGE_RECALCULATED,
    ISSUE_UPDATED,
    ESCALATION_NOTIFICATION_QUEUED,
    ESCALATION_NOTIFICATION_ATTEMPT_FAILED,
    ESCALATION_NOTIFICATION_RETRY_SCHEDULED,
    ESCALATION_NOTIFICATION_SUCCEEDED,
    ESCALATION_NOTIFICATION_FAILED
}
